---
fixtures:
  repositories:
    apache:                "https://github.com/simp/pupmod-simp-apache"
    auditd:                "https://github.com/simp/pupmod-simp-auditd"
    augeasproviders_core:  "https://github.com/simp/augeasproviders_core"
    augeasproviders_grub:  "https://github.com/simp/augeasproviders_grub"
    common:                "https://github.com/simp/pupmod-simp-common"
    concat:                "https://github.com/simp/pupmod-simp-concat"
    iptables:              "https://github.com/simp/pupmod-simp-iptables"
    logrotate:             "https://github.com/simp/pupmod-simp-logrotate"
    pki:                   "https://github.com/simp/pupmod-simp-pki"
    rsync:                 "https://github.com/simp/pupmod-simp-rsync"
    rsyslog:               "https://github.com/simp/pupmod-simp-rsyslog"
    stdlib:                "https://github.com/simp/puppetlabs-stdlib"
    functions:             'https://github.com/simp/pupmod-simp-functions'
  symlinks:
    jenkins: "#{source_dir}"
